# Application Configuration File
---
platform:
  baseUrl: "https://example.cumulocity.com"
  user: "t12345/myuser"
  pass: "mysupersecretpass"

serviceC8yDevice:
  activate: false
  type: "exportService"
  name: "exportService"
  externalIdKey: "c8y_Serial"
  externalIdValue: "exportService"

request:
  dateFrom: "2022-03-21T20:00:00.000Z"
  dateTo: "2022-03-25T20:00:00.000Z"
  source: "407401764"
  chunkSize: 1000

outputFile: "./measurements.csv"
