# Application Configuration File
---
platform:
  baseUrl: "https://example.cumulocity.com"
  user: "t12345/myuser"
  pass: "mysecretpass"
serviceC8yDevice:  # Service is represented as Cumulocity Device holding events/alarms for auditing
  activate: false
  type: exportService
  name: exportService
  externalIdKey: c8y_Serial
  externalIdValue: exportService
request:
  dateFrom: '2021-01-01T00:00:00.000Z'
  dateTo: '2022-04-01T00:00:00.000Z'
  source: '100200'
  chunkSize: 1000
outputFile: ./measurements.csv
